stages:
    - build

build:
    stage: build
    image: registry.motius.de/microservices/kotlin-native
    script:
        - make
    artifacts:
        paths:
            - "build"
    tags:
        - staging-docker
